### ISSUE TITLE
tracing errors in various programs

### ISSUE THREAD

**Issue by asn-the-goblin-slayer** [p-e-w/maybe#5] opened 2016-02-07 03:14 UTC
Hello!

I tried to `maybe` a few programs and had trouble with some. Here are some logs:

     $ maybe /usr/bin/tor
     Feb 07 05:12:58.285 [notice] Tor v0.2.5.12 (git-3731dd5c3071dcba) running on Linux with Libevent 2.0.21-stable, OpenSSL 1.0.1k and Zlib 1.2.8.
     Error tracing process: invalid literal for int() with base 0: '"Feb 07 05:12:58.286 [notice] Tor can\'t help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning\\n"'.
     WARNING:root:Terminate <PtraceProcess #20412>
     
     $ maybe /usr/bin/wicd-client 
     Error tracing process: ptrace(cmd=1, pid=20469, 140724290867200L, 0) error #5: Input/output error.
     WARNING:root:Terminate <PtraceProcess #20469>

Any ideas what's wrong?

**Comment by p-e-w** [comment] 2016-02-07 18:02
The first problem has been fixed in https://github.com/p-e-w/maybe/commit/7511ab9fb6bfdaa6704a3b63fd69d53d7674da56. Please update `maybe` to 0.3.0.

As for the second error, I am currently in the dark about that one.

**Comment by p-e-w** [comment] 2016-02-20 09:19
Second error is a duplicate of https://github.com/p-e-w/maybe/issues/14.

**Closed by p-e-w** 2016-02-20 09:19 UTC
Labels: bug, duplicate
